const SIDEBAR_OPEN = "SIDEBAR_OPEN";
const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
const SIDEBAR_MOBILE_OPEN = "SIDEBAR_MOBILE_OPEN";
const SIDEBAR_MOBILE_CLOSE = "SIDEBAR_MOBILE_CLOSE";

export {
    SIDEBAR_OPEN,
    SIDEBAR_CLOSE,
    SIDEBAR_MOBILE_OPEN,
    SIDEBAR_MOBILE_CLOSE
}