const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
const IS_SIDEBAR_TOGGLE = "IS_SIDEBAR_TOGGLE";
const SIDEBAR_OPEN = "SIDEBAR_OPEN";
const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export {
    SET_SELECTED_PAGE,
    IS_SIDEBAR_TOGGLE,
    SIDEBAR_OPEN,
    SIDEBAR_CLOSE
}