/*
 * action types
 */

const CURRENT_CALENDAR_MONTH = "CURRENT_CALENDAR_MONTH";
const SET_CURRENT_DATE = "SET_CURRENT_DATE"
const NEXT_CALENDAR_MONTH = "NEXT_CALENDAR_MONTH";
const PREV_CALENDAR_MONTH = "PREV_CALENDAR_MONTH";

export {
    CURRENT_CALENDAR_MONTH,
    SET_CURRENT_DATE,
    NEXT_CALENDAR_MONTH,
    PREV_CALENDAR_MONTH
}