/*
 * action types
 */

const CURRENT_CALENDAR_MONTH = "CURRENT_CALENDAR_MONTH";
const NEXT_CALENDAR_MONTH = "NEXT_CALENDAR_MONTH";
const PREV_CALENDAR_MONTH = "PREV_CALENDAR_MONTH";

export default {
    CURRENT_CALENDAR_MONTH,
    NEXT_CALENDAR_MONTH,
    PREV_CALENDAR_MONTH
}